### ISSUE TITLE
Broken NASA logo image reference

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/NASAWorldWind.github.io#101]
The image link to the NASA logo at: https://worldwind.arc.nasa.gov/web/docs/ is invalid. See attached.

![bug](https://user-images.githubusercontent.com/5826820/31041063-14b872e6-a555-11e7-8ad8-08a480a22e22.png)

**Comment by markpet49** [comment]
Note: In FireFox you will see the broken link square, in Chrome you will just see white space.

**Comment by pdavidc** [comment]
FYI, This is an issue with the WebWorldWind's README.md file. The top level page for WebWorldWind's API docs is built, via JSDoc, from the readme file.

**Comment by eirizarry** [comment]
@pdavidc I have made PR in each repo to fix this issue. The path to the image has changed since migrating to Hugo, so I corrected it. 

The PR numbers for this issue are: 
#114, 134, 140, 168, 263.
