### ISSUE TITLE
WorldWind pitch deck refinement

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/NASAWorldWind.github.io#109]

**Comment by eirizarry** [comment]
Second iteration of WorldWind pitch deck. Outcome: Usable pitch deck for presentations and 2-3 pg report of WorldWind. 

- [x] Market Research
- [x] Current traction
- [x] Define growth metrics
- [x] Marketing plan 
- [x] Financials 
- [x] Business model
- [x] Strategy

**Comment by eirizarry** [comment]
Pitch deck is complete and ready for presentation.
