### ISSUE TITLE
Develop dynamic content retrieval and build system

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/NASAWorldWind.github.io#11]
Extend the current NPM based content retrieval mechanisms to integrate into the static site generator.

**Comment by zglueck** [comment]
Hugo provides limited API request capability which eliminates our requirements to retrieve version information.

We still need to resolve the publication of javadocs.

**Comment by pdavidc** [comment]
Publication of Javadocs was resolved with #60. The remaining aspects of this issue have become unnecessary, or have already been incorporated into the site build system.
