### ISSUE TITLE
Travis CI deployment from develop branch

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/NASAWorldWind.github.io#12]
Configure Travis CI to deploy build and deploy pushes on the develop branch. Since this is a GitHub pages Organization/User site, use the built-in Travis CI GitHub pages deployment to publish to the master branch.

**Comment by zglueck** [comment]
A proposal for @pdavidc, @emxsys, @Beak-man, and @eirizarry 

#6 was an effort to reduce the size of the git repository. Our investigation showed that in addition to the daily history, a true driver of the repository size was actually the number of files (driven by the several thousand javadoc files).

The workflow we are currently using may not eliminate this bloat. Since Travis is pushing the dynamically downloaded javadocs to master for website publishing, they are being included in the repository again, albeit, not in the develop branch, but as part of the repo none the less. As we add the different projects documentation, I think we may begin to see the repository bloat.

If there is a real desire to maintain a website repo which contains as little dynamically retrieved content as possible, I propose moving the website repository outside of the GH Pages repo. The website repository would maintain a small footprint and not include the large number of files from documentation. Travis can still publish to the pages repo for website display. The Pages repo purely becomes a collection of files making up the website.

It's not a critical design point but may be convenient to implement at this point. What do you think?

**Comment by pdavidc** [comment]
Zach, I'm not seeing any measurable repository bloat in my local clone of NASAWorldWind.github.io. I think that attempting to optimize further has diminishing returns for us, and could end up complicating the project structure. Given that, I'd recommend that we keep the structure it as-is until we encounter an issue with repository size.

**Comment by pdavidc** [comment]
I've enabled Travis CI for the NASAWorldWind.github.io repository.

Note that the GitHub api key environment variable name has changed to "GITHUB_API_KEY" for consistency with the other repositories.

**Comment by pdavidc** [comment]
This issue completes the migration to the new Hugo based site (#55). Prior to completing the transition, we're conducting a team review of the new site content, and preparing the Apache server at worldwind.arc.nasa.gov (#73).
