### ISSUE TITLE
Track down links/references to worldwindserver.net

### ISSUE THREAD

**Issue by eirizarry** [NASAWorldWind/NASAWorldWind.github.io#120]
Closes #112

- Check website "Web WW"
- Check Web WW repo

**Comment by eirizarry** [comment]
Since all examples have been updated, there are no references to worldwindserver.net in the web repo. 

References in the Web WW repo have also been tracked. 

@pdavidc , are there any other places you would like me to check, or should I close this issue?

**Comment by pdavidc** [comment]
Thanks @eirizarry. Would you please search WorldWindJava and WorldWindAndroid as well?

**Comment by eirizarry** [comment]
Done.
