### ISSUE TITLE
Clear the current repository

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/NASAWorldWind.github.io#21]
The new site will use a substantially different layout than the current one. There needs to be an orderly transition where the old site will stop updating our primary site (https://worldwind.arc.nasa.gov/), but still allow for development of the new static generator based site.

- [x] Turn Off Travis Builds
- [x] Remove Travis `deploy` configuration
- [x] Determine if we want to eliminate the repo history when replacing site

**Comment by pdavidc** [comment]
@zglueck I've turned off travis builds for NASAWorldWind/WorldWind.github.io

**Comment by pdavidc** [comment]
@zglueck I think we want to keep the history of the develop branch. The develop branch is our only history of the original site. The current repo with an empty develop branch is ~30 MB, which is a reasonable overhead in order to preserve this history.
