### ISSUE TITLE
WorldWindServerKit website section

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/NASAWorldWind.github.io#34]
Candidate sections:

- Overview
    - Purpose
        - Vision/Scope
    - Features
        - GeoPackage
        - Integrated GeoWebCache
        - GDAL Formats

- Developer
    - Architecture/Design
        - Module descriptions
        - UML diagrams
    - How to build
        - Maven
        - Github

- User
    - Documentation
        - Export GeoPackage
        - WorldWind Preview
        - Out-of-the-box settings
        - Common Issues/FAQ, e.g., CORS 
    - How to add features
    - How to install/configure
        - Standalone/Jetty
        - Tomcat
        - Memory allocation
        - JAI 
    - How to interface with clients

**Comment by emxsys** [comment]
Added candidate sections.

**Comment by emxsys** [comment]
@eirizarry Added more content to the issue description.

**Comment by eirizarry** [comment]
@emxsys, @pdavidc 

Here are my proposed candidate sections for the WWSK portion of worldwind.arc.nasa.gov. (Rudimentary outline) I believe we can keep the pages for WWSK in the somewhat of the same format as the SDKs. 

Overview (Home)
- Purpose/Vision/Scope 

Get Started 
- How to build 
     - Maven 
     - Github
- How to run 
(Or links to docs page for more detailed instructions) 

Features
- GeoPkg, GeoWebCache, etc. 

Examples (Use Cases) 
- Local and remote data
- Draw data 
- Export data

Docs 
- Module descriptions
- UML diagrams 
- Architecture/Design 
- Export GeoPackage
- WorldWind Preview
- Out-of-the-box settings
- Common Issues/FAQ, e.g., CORS
- How to add features
- How to install/configure
     - Standalone/Jetty
     - Tomcat
     - Memory allocation
     - JAI
     - How to interface with clients

This may not be comprehensive, and this section will develop over time, but these pages would be up by the start of EO Open Science.

**Comment by pdavidc** [comment]
@eirizarry I like this adjustment. The content determines the major categories.

There are a few items under docs that I think belong in another section. I think these items (and others like them) will be useful to folks browsing the site trying to find help. What I have in mind is something like a 'how to' section or like our SDK 'tutorials' that would group items intended to provide guidance on a specific purpose. The items that came to my attention are:
- Export GeoPackage
- Common Issues/FAQ, e.g., CORS
- How to add features
- How to install/configure ...
