### ISSUE TITLE
Mockup and Prototype WorldWind sites

### ISSUE THREAD

**Issue by eirizarry** [NASAWorldWind/NASAWorldWind.github.io#51]
Create a mockup of the WorldWind websites that revises and redesigns the current content. 

Prototype the current [landing page](https://worldwind.arc.nasa.gov/) and [webworldwind.org](https://webworldwind.org/) to test usability and to better understand what full implementation will require. The prototypes will be built using Hugo as the site generator.

**Comment by eirizarry** [comment]
@pdavidc , @zglueck , @emxsys , @Beak-man 

Here is a mock-up of the WorldWind landing page. The social media icons near the bottom were added as possible ways to do outreach. 

![ww-landing-page](https://user-images.githubusercontent.com/23271817/28690012-7f637ea8-72cc-11e7-87f6-9c79b25e4107.jpg)

**Comment by zglueck** [comment]
@eirizarry That looks great!

**Comment by pdavidc** [comment]
I think the the landing page mockup is fantastic.

@PJHogan ought to stay in the loop on this. It would be great to have his feedback as well.

**Comment by emxsys** [comment]
Nice! I'm pleased.

**Comment by eirizarry** [comment]
Overview of Web WorldWind 

![web-worldwind-overview](https://user-images.githubusercontent.com/23271817/28734204-a1bddde0-7394-11e7-8a96-cf43b2a4fad2.jpg)

**Comment by Beak-man** [comment]
Beautiful

**Comment by emxsys** [comment]
An eye for aesthetics, style and contemporary design is on display. I like it.

**Comment by zglueck** [comment]
It is looking good!

**Comment by pdavidc** [comment]
Very nicely done. Like the landing page, the layout and the focus on visual content are a perfect fit for WorldWind. Placing the project's navigation links in the forefront are very nice, while the subtle but effective navigation indicator marks your location in the project space.

**Comment by eirizarry** [comment]
Two more pages under the Web WorldWind section.

Features
![web-worldwind-features](https://user-images.githubusercontent.com/23271817/28837299-1ee96c9e-76a1-11e7-8eb9-56b1eefab18d.jpg)

Get Started
![web-worldwind-getstarted](https://user-images.githubusercontent.com/23271817/28837307-275ec676-76a1-11e7-9372-3400a9c5c021.jpg)

**Comment by eirizarry** [comment]
Prototype can be found [here](https://github.com/eirizarry/NASAWorldWind.github.io/tree/prototype-test).

There are some formatting differences due to the nature of Hugo layouts, but the pages are revised pages are interactive and appropriately linked to the rest of the site.

**Comment by eirizarry** [comment]
Close [#51](https://github.com/NASAWorldWind/NASAWorldWind.github.io/issues/51)
