### ISSUE TITLE
Hugo site per-project API documentation links

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/NASAWorldWind.github.io#57]
Establish per-project API documentation links in the new Hugo based site.

**Comment by pdavidc** [comment]
Per-project API documentation is available at:
https://nasaworldwind.github.io/WebWorldWind/
https://nasaworldwind.github.io/WorldWindAndroid/
https://nasaworldwind.github.io/WorldWindJava/

**Comment by zglueck** [comment]
@pdavidc Thanks!
