### ISSUE TITLE
Hugo site layout and image adjustments

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/NASAWorldWind.github.io#58]
Adjust the layout and images used by the new Hugo based site in preparation for deployment.

**Comment by pdavidc** [comment]
I've identified potential unnecessary files and folders in the Hugo based site:
- ~~/css~~  (css, js, and scss are erroneous holdovers from my local copy of the master branch)
- ~~/js~~
- ~~/scss~~ 
- /archetypes/android.md
- /archetypes/java.md
- /archetypes/server.md
- /archetypes/web.md

**Comment by pdavidc** [comment]
LICENSE.html and LICENSE.txt belong in /static to ensure they're published at the web root.

**Comment by zglueck** [comment]
@pdavidc Should the LICENSE files be in both the repository and static root?

**Comment by pdavidc** [comment]
Thanks for catching that.
- LICENSE.txt belongs where it is now, the project root, per GitHub project conventions.
- LICENSE.html belongs in /static, so it's available at https://worldwind.arc.nasa.gov/LICENSE.html, an existing asset that we reference throughout WorldWind's other projects.
