### ISSUE TITLE
Hugo site WebStorm project

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/NASAWorldWind.github.io#59]
Establish a WebStorm project for the new Hugo based site.

**Comment by pdavidc** [comment]
@zglueck I've had success establishing a WebStorm project in my local environment. I'll establish a branch that we can use to test this in a shared environment. Please let me know if you've encountered any issues or challenges.

**Comment by zglueck** [comment]
@pdavidc I've been using WebStorm for my latest work without issue.

**Comment by pdavidc** [comment]
@zglueck I've established pull request #67 to demonstrate one possible WebStorm project configuration. Would you please compare this with the project you created?
