### ISSUE TITLE
Prototype static site generation

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/NASAWorldWind.github.io#8]
Mock up a small sample of the website to get a better understanding of what a full implementation would require. Check Travis and GitHub Pages integration.

**Comment by eirizarry** [comment]
Comparison of Bootstrap and Foundation frameworks:

[bootstrapfoundationnotes.docx](https://github.com/NASAWorldWind/NASAWorldWind.github.io/files/1089385/bootstrapfoundationnotes.docx)

**Comment by zglueck** [comment]
A full comparison for the three considered generators was conducted and documented here:

https://github.com/zglueck/site-compare/

Prototype generation demonstrated all three generators were capable of meeting our tasks. Hugo provided the best solution for many of our key use cases.
