### ISSUE TITLE
Task definition for WorldWind public channels

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/NASAWorldWind.github.io#80]
Define the tasks and next steps needed for managing WorldWind's public channels:
- worldwind.arc.nasa.gov
- goworldwind.org
- webworldwind.org
- GitHub
- Forum

**Comment by eirizarry** [comment]
**Not yet prioritized**

This task encompasses the following issues: 

[#68](https://github.com/NASAWorldWind/NASAWorldWind.github.io/issues/68): Search Engine Optimization
[#75](https://github.com/NASAWorldWind/NASAWorldWind.github.io/issues/75): Google Analytics implementation

---
All site content will be under: worldwind.arc.nasa.gov 
- Decide what content should be on site
- New way to implement tutorials/examples

GitHub: 
- WorldWind repos need all instances of "World Wind" to be changed. 
- Update/add CONTRIBUTING.md files to all WorldWind repos
          -include: Code of Conduct, Issue Template, PR Template 
- Check error messages output, add [gh_inspector](https://github.com/orta/gh_inspector), which will look through existing GitHub issues for user. 
- Close abandoned issues/PR after period of inactivity
- Update project documentation (and add GitHub wiki)

Enhance/new features: 
- Active management of Twitter account
- Respond to WorldWind-related questions on StackOverflow, redirect to WorldWind forum
- Updates on news/events for WorldWind, GIS, NASA (implemented in next site iteration)
- New WorldWind blog
- Next full WorldWind site needs complete mockup portfolio before being built
- Enhanced Forum UI
- New way to view javadocs (not high priority, but can keep task in our line of sight)

Potential Social/Communication Platforms: 
- Slack
- Facebook
- LinkedIn
- YouTube

**Comment by eirizarry** [comment]
Google Analytics has been successfully implemented via PR [#84](https://github.com/NASAWorldWind/NASAWorldWind.github.io/pull/84).
