### ISSUE TITLE
Add Site Maps

### ISSUE THREAD

**Issue by eirizarry** [NASAWorldWind/NASAWorldWind.github.io#91]
Closes #89

The website should have two different site maps--one for users and one for search bots. 

This issue is a two-step process: 

1. Create a site map for users and implement it into the site
2. Check the existing .xml site map ensure that it is in the proper format

**Comment by eirizarry** [comment]
@pdavidc I believe we've have a brief discussion about site maps, and you showed me the auto-generated hugo .xml site map. I don't know if I'm missing the obvious, but I can't seem to find it.

**Comment by pdavidc** [comment]
The auto-generated Hugo site map is a product of the build. You'll need to look at your local build output, or check out the master branch:
https://github.com/NASAWorldWind/NASAWorldWind.github.io/tree/master

**Comment by eirizarry** [comment]
Got it, thanks! The auto-generated site map looks good to me.
