### ISSUE TITLE
Incorporate credit for products with free licenses 

### ISSUE THREAD

**Issue by eirizarry** [NASAWorldWind/NASAWorldWind.github.io#95]
We are currently using several products for which we've obtained free licenses. Credit for this usage needs to be incorporated into worldwind.arc.nasa.gov. 

Licenses that need to be incorporated include: 
- IntelliJ IDEA
- WebStorm 
- Install4J

Credit for these licenses will be given on the "Overview" Pages for WWJava, Web WW, and WWSK, respectively.

**Comment by emxsys** [comment]
### Server Kit Credits

On the Server Kit overview page, please add a link to https://www.ej-technologies.com/products/install4j/overview.html

Preferably, the link should be a text link including the words "multi-platform installer builder". The link must not contain the "nofollow" attribute.  Please use the following image for an icon or a different image available from https://www.ej-technologies.com/buy/install4j/openSource .

![image](https://user-images.githubusercontent.com/191515/31437522-67d73352-ae3a-11e7-8ef9-11746aa9495e.png)

**Comment by pdavidc** [comment]
@eirizarry Please check for an SVG version of this image.
